Add output time interval
chaos-polymtl/lethe pull request #1120
Opened 2024-05-07 19:12 UTC by mivaia

# Description of the problem

- Only needed the last 30% of my simulations and they are quite heavy.

# Description of the solution

- Added a new parameter in the parameter file -> output_time_interval. If the user specifies an output time interval, the .vtu files are only written if the simulation time is within that time window. This has been implemented for output control = iteration and output control = time.

# How Has This Been Tested?

- new simulation_control_06.cc test. Makes sure information is written at the appropriated time steps.

# Documentation

- Modified the simulation_control.rst file to consider the new parameter.

2024-05-07 19:24 UTC, blaisb requested changes
Very minor comments
Can you add a CHANGELOG entry?
Thanks :)!

2024-05-07 19:24 UTC, blaisb commented on doc/source/parameters/cfd/simulation_control.rst
> +* ``output time interval``: Only writes the ``.pvd`` / ``.vtu`` files when the simulation time is within ``output time interval``. Default values are 0s and 1.7e308s.
```suggestion
* ``output time interval``: Only writes the ``.pvd`` / ``.vtu`` files when the simulation time is within the closed interval defined by the ``output time interval``. Default values are 0s and 1.7e308s.
```

2024-05-07 19:24 UTC, blaisb commented on tests/core/simulation_control_06.cc
> +* Author: Bruno Blais, Polytechnique Montreal, 2020-
```suggestion

```

2024-05-07 19:24 UTC, blaisb commented on tests/core/simulation_control_06.cc
> + */
Are you sure about this comment? I don't think this is what this test is checking

2024-05-07 20:34 UTC, oguevremont commented on include/core/simulation_control.h
> +  // Output file will be generated if current step number is in the output time
The phrasing is a bit confusing. I'd say that this adds another condition for the output (in addition to the step respecting the output frequency parameter).

2024-05-08 17:57 UTC, mivaia reviewed
Thank you for your comments! All of them have been adressed :)

2024-05-08 18:46 UTC, oguevremont approved these changes

2024-05-08 22:31 UTC, merged