Modify viscosity in stabilization tau
chaos-polymtl/lethe pull request #1126
Opened 2024-05-09 21:17 UTC by hepap

# Description of the problem

- For phase change problem, the viscosity used in the tau computation for the stabilization in the solid used the numerical solid viscosity. Since this solid viscosity has no physical meaning, it was weird to used it, and the linear solver seemed to converge slower.

# Description of the solution

- Introduce new attributes in NS scratch data `kinematic_viscosity_for_stabilization` and `dynamic_viscosity_for_stabilization`. Both are compute by the rheology model. For now, except in the phase change, it returns the current viscosity. However, in the phase change rheology model, it returns the liquid viscosity.

# How Has This Been Tested?

- The melting cavity case was used to insure that the results stay the same and to show better convergence of the linear solver.

- [x] heat_transfer_phase_change_constrain_solid_domain
- [x] heat_transfer_vof_phase_change_constrain_solid_domain

Those two tests were changed to have a more representative behaviour.

# Future changes

- Test the viscosity scale in VOF and non-newtonian cases to see if it brings some gains

2024-05-15 13:45 UTC, PierreLaurentinCS reviewed
Very nice additions, I left some questions here and there but overall it's a great work!

2024-05-15 17:41 UTC, PierreLaurentinCS requested changes
See my previous comments for requested changes, then it'll be good to go :)

2024-05-15 18:02 UTC, hepap commented on applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.output
> +Pressure drop: -1.51849e-18 Pa
My guess would be that in the first time step (smaller than it use to be), there is not much melted fluid, so no motion and no pressure drop. What do you think @blaisb?

2024-05-16 12:58 UTC, PierreLaurentinCS approved these changes
Good!

2024-05-16 12:58 UTC, PierreLaurentinCS commented on include/core/rheological_model.h
> +    return param.kinematic_viscosity_l;
This makes much more sense, thanks

2024-05-16 15:42 UTC, blaisb approved these changes

2024-05-16 15:42 UTC, blaisb commented
@hepap can you rebase? This will then be ready for merge

2024-05-17 13:02 UTC, hepap commented
@blaisb it's rebased!

2024-05-17 13:45 UTC, blaisb commented
@hepap something went wrong in your rebase I think

2024-05-17 18:38 UTC, merged