Robin/Neumann BC parameters were not space dependent
chaos-polymtl/lethe pull request #1128
Opened 2024-05-11 04:50 UTC by voferreira

# Description of the problem

- The convection-radiation-flux boundary condition had function expression parameters that were not space dependent.

# Description of the solution

- Made it space-dependent using the function evaluation at the quadrature point position.

# How Has This Been Tested?

- Simple 2D heat flux case. The test was added to the application tests.

# Documentation

- [ ] Remove disclaimer from parameters guide regarding the no longer existent limitation.

# Comments

- This PR is a follow up of PR #1000 .
- There is no way to have ``set number of fluids = 0``. This was added to the maintenance project and I will fix it in another PR.

2024-05-11 05:43 UTC, blaisb requested changes
Very cool work. Since it'S not a lot of work and while you are at it, cna you also ensure that the set-time is called also to set up the current value of the time?

2024-05-11 05:43 UTC, blaisb commented on applications_tests/lethe-fluid/non-uniform_heat_flux_bc.output
> +  -Iterative solver took : 16 steps to reach a residual norm of 4.55329e-05
Tolerances and linear solver verbosity should not be in the test because these are not portable :)

2024-05-11 05:43 UTC, blaisb commented on applications_tests/lethe-fluid/non-uniform_heat_flux_bc.prm
> +end
Can you run prm indent, seems like it needs to be run :)

2024-05-11 05:43 UTC, blaisb commented on applications_tests/lethe-fluid/non-uniform_heat_flux_bc.prm
> +    set ilu preconditioner relative tolerance = 1.00
```suggestion

```
default parameters are ok here I think

2024-05-11 05:43 UTC, blaisb commented on applications_tests/lethe-fluid/non-uniform_heat_flux_bc.prm
> +    set tolerance      = 1e-1
This is very big for a tolerance, why is it so big? I would lower it :)

2024-05-11 05:43 UTC, blaisb commented on applications_tests/lethe-fluid/non-uniform_heat_flux_bc.prm
> +    set ilu preconditioner relative tolerance = 1.00
Maybe a good idea to check some other sections to keep it to the minimal, at least as best as you can

2024-05-11 05:43 UTC, blaisb commented on source/solvers/heat_transfer_assemblers.cc
> +                          scratch_data.quadrature_points[q][d];
Why do you need to make a local copy of the points? why not just juse teh points directly?

2024-05-11 20:33 UTC, voferreira commented
@blaisb Thanks! I thought set_time was called on update_boundary_conditions, but the if in the integration was preventing it from being called. This is fixed now. Plus I have placed the assertion for the emissivity at the right place, I believe. I also added a transient test for heat_flux = 10*t*y.

2024-05-12 21:54 UTC, blaisb approved these changes
One last comment and then ready for merge

2024-05-12 21:54 UTC, blaisb commented on source/solvers/heat_transfer_assemblers.cc
> +                             EmissivityError(emissivity));
Since  you are declaring an exception don't you want to call AssertThrow instead of just Assert?

2024-05-13 22:17 UTC, blaisb commented
I'll let @mivaia take a look at it and then if he's ok with it I'll merge

2024-05-14 12:54 UTC, mivaia approved these changes
All good on my side! Thanks for giving me some time to look into it :)

2024-05-14 19:33 UTC, merged