Add missing VOF term in the strong form of the residual
chaos-polymtl/lethe pull request #1149
Opened 2024-05-20 22:22 UTC by blaisb

# Description of the problem

- There was a missing term in the strong form of the residual which is (mu_1 - mu_0) * (grad_u + grad_u^T) * grad_phase
- This does not have significant consequences, but I think it is best to remain consistent

# Description of the solution

- Add missing term

# How Has This Been Tested?

- All test results barely change, but I had to update them nonetheless
- It seems to help a little bit in terms of velocity divergence, but really not much to be honest.

2024-05-20 22:24 UTC, blaisb commented on source/solvers/navier_stokes_vof_assemblers.cc
> +
```suggestion
```

2024-05-20 22:24 UTC, blaisb commented on source/solvers/navier_stokes_vof_assemblers.cc
> +              const auto  shear_rate_j = grad_phi_u_j + transpose(grad_phi_u_j);
This should not have been a reference, so this was a bit weird.

2024-05-22 14:43 UTC, AmishgaAlphonius approved these changes
Funny that it was not thought of before! I only found a small typo to fix :)

2024-05-22 14:43 UTC, AmishgaAlphonius commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:43 UTC, AmishgaAlphonius commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:43 UTC, AmishgaAlphonius commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:43 UTC, AmishgaAlphonius commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:54 UTC, lpsaavedra approved these changes
I have only a small comment. These equations are not in the documentation, am I correct? I guess we should be writing these equations there soon in a "multiphysics coupling" section...

2024-05-22 14:54 UTC, lpsaavedra commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:54 UTC, lpsaavedra commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:54 UTC, lpsaavedra commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:54 UTC, lpsaavedra commented on source/solvers/navier_stokes_vof_assemblers.cc
> +      // Void fraction gradient for strong residual
```suggestion
      // Filtered phase fraction gradient for strong residual
```

2024-05-22 14:57 UTC, PierreLaurentinCS requested changes
Nothing to say, everything is clean, but I'd like this question answered before merging : 
Why don't we add the term also in the strong jacobian ?

2024-05-22 15:49 UTC, hepap approved these changes

2024-05-22 18:12 UTC, blaisb commented on applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
> +1.000000 0.512900 0.576332 0.363353 0.013339
Yeah I was wondering this also. I'm not exactly sure what's up. I'll double check.

2024-05-22 18:13 UTC, blaisb commented
> Nothing to say, everything is clean, but I'd like this question answered before merging : Why don't we add the term also in the strong jacobian ?

Good question. The strong Jacobian term is very expensive to calculate since it has the full hessian. I checked many cases and it never really affects convergence, so for now we can neglect it i think.

2024-05-22 18:28 UTC, PierreLaurentinCS approved these changes

2024-05-28 18:21 UTC, blaisb commented on applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
> +1.000000 0.512900 0.576332 0.363353 0.013339
Yeah that test is weird as fuck, I'm not surpirsed the results changed that much, the test has not real physical meaning it's just there to see if the boundary change in time. No alarm to be had.

2024-05-29 17:17 UTC, merged