Post processing pressure power and viscous dissipation
chaos-polymtl/lethe pull request #1157
Opened 2024-05-25 19:30 UTC by blaisb

# Description of the problem

- For the analysis of the turbulent taylor-couette problem we need to be able to postprocess the power of the pressure (\nabla p \cdot u) and the viscous dissipation (\tau \cdot \nabla u) in order to do the full kinetic energy balance

# Description of the solution

- Added both features as well as their tables and serialization
- Modified the application test for taylor couette to include the viscous dissipation. If you multiply the viscous dissipation by the volume of the triangulation you get exactly the torque * the angular velocity, which is exactly what we expect
- Added the documentation of the features.

# Comments

- I took the opportunity to make some more things const that should have been const
-

2024-05-27 17:07 UTC, lpsaavedra requested changes
Nice improvements... just a few small comments from my side

2024-05-27 21:12 UTC, PierreLaurentinCS requested changes
Very good job, I just want to make sure there is no confusion between power and work of pressure

2024-05-27 21:12 UTC, PierreLaurentinCS commented on source/solvers/postprocessing_cfd.cc
> +  return (pressure_work);
Why the parenthesis around the returned variable? Is it for aesthetic?

2024-05-27 21:12 UTC, PierreLaurentinCS commented on source/solvers/postprocessing_cfd.cc
> +  return (viscous_dissipation);
Why the parenthesis around the returned variable? Is it for aesthetic?

2024-05-28 12:08 UTC, blaisb commented on include/core/parameters.h
> +    /// Enable pressure work post-processing
Yes it's power everywhere, power is the right terminology I made the mistake at first

2024-05-28 14:34 UTC, lpsaavedra requested changes
Some additional minor comments

2024-05-28 15:04 UTC, lpsaavedra approved these changes

2024-05-28 15:44 UTC, blaisb commented
@PierreLaurentinCS I need your approval before I cna merge

2024-05-28 15:54 UTC, PierreLaurentinCS approved these changes
Everything is good for me! Good job :thumbsup: :thumbsup: :thumbsup:

2024-05-28 17:07 UTC, merged