Different improvements for AMS
chaos-polymtl/lethe pull request #1253
Opened 2024-08-20 21:06 UTC by peterrum

- setup: compute weights during initialization and convert indices from global to local
- add timers
- reused smoother preconditioner instances

2024-08-21 13:24 UTC, lpsaavedra approved these changes

2024-08-22 00:36 UTC, blaisb requested changes
Just a few things to fix

2024-08-22 00:36 UTC, blaisb commented on source/solvers/fluid_dynamics_matrix_free.cc
> +    this->timer.enter_subsection("asm::restrict");
```suggestion
    this->timer.leave_subsection("asm::indices");
    this->timer.enter_subsection("asm::restrict");
```

2024-08-22 00:36 UTC, blaisb commented on source/solvers/fluid_dynamics_matrix_free.cc
> +   */
Can you add @param for the parameters

2024-08-22 00:36 UTC, blaisb commented on source/solvers/fluid_dynamics_matrix_free.cc
> +   */
can you add @param

2024-08-22 00:36 UTC, blaisb commented on source/solvers/fluid_dynamics_matrix_free.cc
>     */
Can you add @param

2024-08-23 15:27 UTC, peterrum commented
@blaisb Ready from my side!

2024-08-23 15:34 UTC, blaisb approved these changes
Awesome. I rebased. Will merge after CI.

2024-08-23 17:28 UTC, merged