Prevent refinement of the boundary when using kelly refinement
chaos-polymtl/lethe pull request #1317
Opened 2024-10-11 18:53 UTC by mivaia

### Description

Mesh adaptation was coarsening the mesh on the boundary when using the kelly estimator for the mesh refinement. This lead to "jumpy" results at the boundary.

### Testing

No tests yet.

### Documentation

Modified the mesh.rst file to take this new feature into account. 

### Miscellaneous (will be removed when merged)

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [ ] All in-code documentation related to this PR is up to date (Doxygen format)
- [ ] Copyright headers are present and up to date
- [ ] Lethe documentation is up to date
- [ ] New feature has unit test(s) (preferred) or application test(s), and restart files are in the generator folder
- [ ] The branch is rebased onto master
- [ ] Changelog (CHANGELOG.md) is up to date
- [ ] Code is indented with indent-all and .prm files (examples and tests) with prm-indent

Pull request related list:
- [ ] Labels are applied
- [ ] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [ ] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [ ] If the fix is temporary, an issue is opened
- [ ] The PR description is cleaned and ready for merge

2024-10-11 19:11 UTC, blaisb requested changes
Great work. If you have an idea of a quick test, it could be relevant to add an application test to check that the feature is good.
Could you also at least add the parameter in the documentation? :) Thank you

2024-10-15 13:33 UTC, mivaia commented
Some comments/questions

1. I added a test that compares the number of elements with the new feature. Should I do one that exactly compares the mesh?
2. I think I updated the doc, is there somewhere I forgot to modify? 
3. The feature is in the mesh subsection, do you think it would be more interesting to have it in the mesh adaptation section?

2024-10-15 14:09 UTC, blaisb commented
> Some comments/questions
> 
> 1. I added a test that compares the number of elements with the new feature. Should I do one that exactly compares the mesh?
I think the test you added is fine. The goal is just to show that you obtain a different number of cells with this feature :). Just to have something that tests the feature.

> 2. I think I updated the doc, is there somewhere I forgot to modify?
Nope the doc update is fine.

> 3. The feature is in the mesh subsection, do you think it would be more interesting to have it in the mesh adaptation section?

I think it is better to put it in the mesh adaptation section in my opinion, but it works in both section. However, since it's related to dynamic adaptation, best put it in that section.

2024-10-19 16:04 UTC, blaisb approved these changes

2024-10-19 16:05 UTC, merged