Refactor vof curvature l2 projection
chaos-polymtl/lethe pull request #1336
Opened 2024-11-01 12:47 UTC by AmishgaAlphonius

### Description

Following PR #1318, this one refactors the curvature projection to be assembled and solved through the VOF subequations interface. Assembly of the matrix and right-hand side for both VOFSubequations (phase fraction gradient and curvature projection) are now done in the same loop without the WorkStream method, as they are pretty simple to assemble.

### Testing

The unit test dedicated to the interface has been updated.
Visual inspection of data was done with the rising bubble case using paraview.

### Miscellaneous (will be removed when merged)

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [ ] All in-code documentation related to this PR is up to date (Doxygen format)
- [ ] Copyright headers are present and up to date
- [ ] Lethe documentation is up to date
- [ ] The branch is rebased onto master
- [ ] Code is indented with indent-all and .prm files (examples and tests) with prm-indent
- [ ] If parameters are modified, the tests and the documentation of examples are up to date
- [ ] Changelog (CHANGELOG.md) is up to date if the refactor affects the user experience or the codebase

Pull request related list:
- [ ] No other PR is open related to this refactoring
- [ ] Labels are applied
- [ ] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [ ] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [ ] If any future works is planed, an issue is opened
- [ ] The PR description is cleaned and ready for merge

2024-11-04 16:55 UTC, blaisb requested changes
Last few changes, quasi nothing. Very good work.

2024-11-04 16:55 UTC, blaisb commented on include/solvers/vof_subequations_interface.h
>  enum VOFSubequationsID : unsigned int
can you make this an enum class or it needs to be an enum?

2024-11-04 16:55 UTC, blaisb commented on include/solvers/vof_subequations_interface.h
> +      subequation_string = "VOF curvature L2 projection";
what is the subequation string used for?

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof.cc
> -template <int dim>
Nice cleanup this is great.

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_curvature_projection.cc
> +
No need to pre-declare it, declare it when you get it.

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_curvature_projection.cc
> +          h = compute_cell_diameter<dim>(compute_cell_measure_with_JxW(JxW_vec),
```suggestion
          const double h = compute_cell_diameter<dim>(compute_cell_measure_with_JxW(JxW_vec),
```

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_curvature_projection.cc
> +VOFCurvatureProjection<dim>::assemble_system_matrix_and_rhs()
This is nice and easy to read, good job

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_phase_gradient_projection.cc
> +
Same here, declare h when you need it.

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_phase_gradient_projection.cc
> +VOFPhaseGradientProjection<dim>::assemble_system_matrix_and_rhs()
This is very easy to read, thanks

2024-11-04 16:55 UTC, blaisb commented on source/solvers/vof_phase_gradient_projection.cc
> +          h = compute_cell_diameter<dim>(compute_cell_measure_with_JxW(JxW_vec),
```suggestion
          const double h = compute_cell_diameter<dim>(compute_cell_measure_with_JxW(JxW_vec),
```

2024-11-04 19:04 UTC, oguevremont approved these changes
Looks good!

2024-11-04 19:18 UTC, hepap approved these changes
Not a lot of comments! I like this new interface a lot!

2024-11-06 12:51 UTC, blaisb approved these changes

2024-11-06 12:51 UTC, merged