Fix bugs: changing time step after restart and tracer tanh model
chaos-polymtl/lethe pull request #1343
Opened 2024-11-07 14:59 UTC by oguevremont

### Description

### Solution

### Testing

### Documentation

### Miscellaneous (will be removed when merged)

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [ ] All in-code documentation related to this PR is up to date (Doxygen format)
- [ ] Copyright headers are present and up to date
- [ ] Lethe documentation is up to date
- [ ] Fix has unit test(s) (preferred) or application test(s), and restart files are in the generator folder
- [ ] The branch is rebased onto master
- [ ] Changelog (CHANGELOG.md) is up to date
- [ ] Code is indented with indent-all and .prm files (examples and tests) with prm-indent

Pull request related list:
- [ ] Labels are applied
- [ ] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [ ] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [ ] If the fix is temporary, an issue is opened
- [ ] The PR description is cleaned and ready for merge

2024-11-08 15:59 UTC, lpsaavedra requested changes
I have a few comments and doubts regarding these new features

2024-11-08 15:59 UTC, lpsaavedra commented on CHANGELOG.md
> +- MINOR Application of the immersed solid tanh diffusivity model is now faster thanks to using optimizations from the Shape class. [#1343](https://github.com/chaos-polymtl/lethe/pull/1343)
```suggestion
- MINOR Time step can now be changed after a restart if adaptive time stepping is disabled. [#1343](https://github.com/chaos-polymtl/lethe/pull/1343)

- MINOR Application of the immersed solid tanh diffusivity model is now faster thanks to using optimizations from the Shape class. [#1343](https://github.com/chaos-polymtl/lethe/pull/1343)
```

2024-11-12 14:05 UTC, oguevremont commented on source/core/simulation_control.cc
> +    set_current_time_step(initial_time_step);
Yes it is risky business, but the way I use it is that I solve NS with small time steps, until the solution is steady, then I solve only tracer with large time steps after a restart (before and after the restart the time step is fixed). I should write this somewhere so it is clearer, thanks for pointing it out

2024-11-18 15:07 UTC, lpsaavedra approved these changes
I just have one additional minor comment...

2024-11-18 15:07 UTC, lpsaavedra commented on CHANGELOG.md
> +### Fix
```suggestion
### Fixed
```

2024-11-18 16:46 UTC, blaisb approved these changes
Much better this way I like it

2024-11-18 16:46 UTC, merged