Examples update for gas-solid fluidized and spouted-bed
chaos-polymtl/lethe pull request #1370
Opened 2024-11-18 22:06 UTC by OresteMarquis

### Description

Update of the .prm and .rst files of the gas-solid fluidized and spouted-bed examples for the Lethe 1.0 release.

### Miscellaneous (will be removed when merged)

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [x] Lethe documentation is up to date
- [x] Copyright headers are present and up to date
- [x] The branch is rebased onto master
- [x] Code is indented with indent-all and .prm files (examples and tests) with prm-indent
- [x] Links are added to parent .rst files
- [x] The example is following the [standard format](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#general-rules-and-format)

Pull request related list:
- [x] Labels are applied
- [x] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [x] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [x] If any future works is planned, an issue is opened
- [x] The PR description is cleaned and ready for merge

2024-11-19 01:21 UTC, blaisb requested changes
Some comments there and there. A generic piece of advice @OresteMarquis is to put as little parameters as possible in the prm file. If the parameter is not modified, then don't put it in the paramter file, the default value will be fine :)

2024-11-19 15:26 UTC, blaisb commented on examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
> +  set bound void fraction = true
I would change both to false.
It's better to trust the prm file and not the rst file for the parameters.

2024-11-19 15:26 UTC, blaisb commented
> How can I know what is the default, so I know what can be removed? I haven't used Lethe enough to know them.

The default values are in the prm template that can be generated with the template parameter executable. I'll show you later if you want.

2024-11-19 15:42 UTC, OresteMarquis commented on examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
> +  set bound void fraction = true
Good to know, I changed it to false everywhere!

2024-11-20 19:20 UTC, blaisb approved these changes

2024-11-20 19:20 UTC, merged